name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build 📦🚧🤖
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.17 💻
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code 🐢
      uses: actions/checkout@v2

    - name: Download dependencies 📦
      run: go mod download

    - name: Build 🚧
      run: go build -v ./...

    - name: Test 🤖
      run: go test -v ./...
